image: clever/drone-node:6.2.2
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  npm:
    token: $$npm_token
    when:
      branch: master
script:
- npm install
- make test
- make build
