apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tracing-middleware
  description: Moved to opentracing-contrib org
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
